//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationServer.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthenticationServer.Resources.Errors", typeof(Errors).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_INACTIVE.
        /// </summary>
        internal static string ACCOUNT_INACTIVE {
            get {
                return ResourceManager.GetString("ACCOUNT_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is inactive.
        /// </summary>
        internal static string ACCOUNT_INACTIVE_MSG {
            get {
                return ResourceManager.GetString("ACCOUNT_INACTIVE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_NOT_FOUND.
        /// </summary>
        internal static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account cannot be found.
        /// </summary>
        internal static string ACCOUNT_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_ALREADY_IN_USE.
        /// </summary>
        internal static string EMAIL_ALREADY_IN_USE {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email has been used by another user.
        /// </summary>
        internal static string EMAIL_ALREADY_IN_USE_MSG {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_IN_USE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_NOT_NULL.
        /// </summary>
        internal static string EMAIL_NOT_NULL {
            get {
                return ResourceManager.GetString("EMAIL_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được trống.
        /// </summary>
        internal static string EMAIL_NOT_NULL_MSG {
            get {
                return ResourceManager.GetString("EMAIL_NOT_NULL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTERNAL_LOGIN_EXIST.
        /// </summary>
        internal static string EXTERNAL_LOGIN_EXIST {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login has been already linked with another account.
        /// </summary>
        internal static string EXTERNAL_LOGIN_EXIST_MSG {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTERNAL_LOGIN_REQUIRED.
        /// </summary>
        internal static string EXTERNAL_LOGIN_REQUIRED {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login is required.
        /// </summary>
        internal static string EXTERNAL_LOGIN_REQUIRED_MSG {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_REQUIRED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT_LOGIN.
        /// </summary>
        internal static string INCORRECT_LOGIN {
            get {
                return ResourceManager.GetString("INCORRECT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect.
        /// </summary>
        internal static string INCORRECT_LOGIN_MSG {
            get {
                return ResourceManager.GetString("INCORRECT_LOGIN_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_ROLE_COMMAND_DATA.
        /// </summary>
        internal static string INVALID_ACCOUNT_ROLE_COMMAND_DATA {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ROLE_COMMAND_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data for account role command is invalid.
        /// </summary>
        internal static string INVALID_ACCOUNT_ROLE_COMMAND_DATA_MSG {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ROLE_COMMAND_DATA_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PHONE_NUMBER.
        /// </summary>
        internal static string INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided phone number is invalid.
        /// </summary>
        internal static string INVALID_PHONE_NUMBER_MSG {
            get {
                return ResourceManager.GetString("INVALID_PHONE_NUMBER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_REGISTRATION_DATA.
        /// </summary>
        internal static string INVALID_REGISTRATION_DATA {
            get {
                return ResourceManager.GetString("INVALID_REGISTRATION_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration data is invalid.
        /// </summary>
        internal static string INVALID_REGISTRATION_DATA_MSG {
            get {
                return ResourceManager.GetString("INVALID_REGISTRATION_DATA_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_REQUEST.
        /// </summary>
        internal static string INVALID_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid.
        /// </summary>
        internal static string INVALID_REQUEST_MSG {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ROLE_BINDING_DATA.
        /// </summary>
        internal static string INVALID_ROLE_BINDING_DATA {
            get {
                return ResourceManager.GetString("INVALID_ROLE_BINDING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role data is invalid.
        /// </summary>
        internal static string INVALID_ROLE_BINDING_DATA_MSG {
            get {
                return ResourceManager.GetString("INVALID_ROLE_BINDING_DATA_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ROLE_PERMISSION_COMMAND_DATA.
        /// </summary>
        internal static string INVALID_ROLE_PERMISSION_COMMAND_DATA {
            get {
                return ResourceManager.GetString("INVALID_ROLE_PERMISSION_COMMAND_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data for role permission command is invalid.
        /// </summary>
        internal static string INVALID_ROLE_PERMISSION_COMMAND_DATA_MSG {
            get {
                return ResourceManager.GetString("INVALID_ROLE_PERMISSION_COMMAND_DATA_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD_PASSWORD_INCORRECT.
        /// </summary>
        internal static string OLD_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        internal static string OLD_PASSWORD_INCORRECT_MSG {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INCORRECT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_NOT_NULL.
        /// </summary>
        internal static string PASSWORD_NOT_NULL {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not null.
        /// </summary>
        internal static string PASSWORD_NOT_NULL_MSG {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_NULL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMISSION_NOT_FOUND.
        /// </summary>
        internal static string PERMISSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("PERMISSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission cannot be found.
        /// </summary>
        internal static string PERMISSION_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("PERMISSION_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN_NOT_NULL.
        /// </summary>
        internal static string PIN_NOT_NULL {
            get {
                return ResourceManager.GetString("PIN_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code is not null.
        /// </summary>
        internal static string PIN_NOT_NULL_MSG {
            get {
                return ResourceManager.GetString("PIN_NOT_NULL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN_NOT_VERIFY.
        /// </summary>
        internal static string PIN_NOT_VERIFY {
            get {
                return ResourceManager.GetString("PIN_NOT_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code has not verified yet.
        /// </summary>
        internal static string PIN_NOT_VERIFY_MSG {
            get {
                return ResourceManager.GetString("PIN_NOT_VERIFY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST_NOT_NULL.
        /// </summary>
        internal static string REQUEST_NOT_NULL {
            get {
                return ResourceManager.GetString("REQUEST_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not null.
        /// </summary>
        internal static string REQUEST_NOT_NULL_MSG {
            get {
                return ResourceManager.GetString("REQUEST_NOT_NULL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLE_DUPLICATED_NAME.
        /// </summary>
        internal static string ROLE_DUPLICATED_NAME {
            get {
                return ResourceManager.GetString("ROLE_DUPLICATED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name has been already used for another role.
        /// </summary>
        internal static string ROLE_DUPLICATED_NAME_MSG {
            get {
                return ResourceManager.GetString("ROLE_DUPLICATED_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLE_NOT_FOUND.
        /// </summary>
        internal static string ROLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role cannot be found.
        /// </summary>
        internal static string ROLE_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("ROLE_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN_IS_EXPIRED.
        /// </summary>
        internal static string TOKEN_IS_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_IS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn đổi mật khẩu đã hết.
        /// </summary>
        internal static string TOKEN_IS_EXPIRED_MSG {
            get {
                return ResourceManager.GetString("TOKEN_IS_EXPIRED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN_NOT_NULL.
        /// </summary>
        internal static string TOKEN_NOT_NULL {
            get {
                return ResourceManager.GetString("TOKEN_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not null.
        /// </summary>
        internal static string TOKEN_NOT_NULL_MSG {
            get {
                return ResourceManager.GetString("TOKEN_NOT_NULL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME_ALREADY_IN_USE.
        /// </summary>
        internal static string USERNAME_ALREADY_IN_USE {
            get {
                return ResourceManager.GetString("USERNAME_ALREADY_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name has been used by another user.
        /// </summary>
        internal static string USERNAME_ALREADY_IN_USE_MSG {
            get {
                return ResourceManager.GetString("USERNAME_ALREADY_IN_USE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION_EXPIRED.
        /// </summary>
        internal static string VERIFICATION_EXPIRED {
            get {
                return ResourceManager.GetString("VERIFICATION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification of phone number has been expired.
        /// </summary>
        internal static string VERIFICATION_EXPIRED_MSG {
            get {
                return ResourceManager.GetString("VERIFICATION_EXPIRED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION_FAILED.
        /// </summary>
        internal static string VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION_LOCKED.
        /// </summary>
        internal static string VERIFICATION_LOCKED {
            get {
                return ResourceManager.GetString("VERIFICATION_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification has been locked.
        /// </summary>
        internal static string VERIFICATION_LOCKED_MSG {
            get {
                return ResourceManager.GetString("VERIFICATION_LOCKED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION_NOT_FOUND.
        /// </summary>
        internal static string VERIFICATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("VERIFICATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification of phone number cannot be found.
        /// </summary>
        internal static string VERIFICATION_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("VERIFICATION_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIT_FOR_VERIFICATION.
        /// </summary>
        internal static string WAIT_FOR_VERIFICATION {
            get {
                return ResourceManager.GetString("WAIT_FOR_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has not been verified yet.
        /// </summary>
        internal static string WAIT_FOR_VERIFICATION_MSG {
            get {
                return ResourceManager.GetString("WAIT_FOR_VERIFICATION_MSG", resourceCulture);
            }
        }
    }
}
